### ISSUE TITLE
Crystallised Honey should be spelt differently in the en_us.json language file

### ISSUE THREAD

**Issue by thisisthedogtor** [DylanLewisGitHub/The-Potato-Pack#1]
Crystallised Honey is the UK spelling, whereas Crystallized Honey (with a 'z') is the way it's spelt in US English. Fixing the "bug" in en_us and creating an additional language file for en_gb (with Crystallised Honey being spelt with a 's') seems appropriate.

**Comment by DylanLewisGitHub** [comment]
It do be a little silly. Fixed it tho
